### ISSUE TITLE
Please add the scripts/commands used to produce this

### ISSUE THREAD

**Issue by adam-funk** [johnlinp/meme-ocr#5]
I'm trying to do something similar. I can generate my own matching *.tif and *.box files, but am struggling to get the tesseract training commands to work. It would be very helpful if you could post the scripts or command sequences that you used to produce the traineddata file successfully.

**Comment by muety** [comment]
+1 I'd love to have the training data!

**Comment by johnlinp** [comment]
Because of my carelessness, I lost all the required training data to reproduce the tessdata. While I was trying to reconstruct the training data, I found this Tesseract user guide: https://tesseract-ocr.github.io/tessdoc/ImproveQuality. After reading it, I think I have some reason not to continue the reconstruction of the training data:

1. After fixing #9, the performance of using built-in tessdata is good enough.
1. IIRC, the current dedicated tessdata in this repo was trained with the font "Impact". Nothing magic inside.
1. The built-in tessdata contains about 4500 fonts, including the "Impact" font.
1. The quote from the user guide:
> There are a variety of reasons you might not get good quality output from Tesseract. It’s important to note that, unless you’re using a very unusual font or a new language, retraining Tesseract is unlikely to help.

So, sorry guys. I won't provide the training data or any script in this repo, for now.
